import React, { createContext, useContext, useState } from 'react';

export const translations = {
    en: {
        'nav.dashboard': 'Dashboard',
        'nav.profile': 'Profile',
        'nav.notices': 'Notices',
        'nav.payments': 'Payments',
        'nav.documents': 'Documents',
        'nav.condominium': 'Condominium',
        'nav.users': 'Users',
        'nav.signOut': 'Sign Out',
        'nav.languageToggle': 'PT',

        'auth.signIn.title': 'Welcome Back',
        'auth.signIn.emailLabel': 'Email Address',
        'auth.signIn.passwordLabel': 'Password',
        'auth.signIn.submit': 'Sign In',
        'auth.signIn.loading': 'Signing In...',
        'auth.signIn.switchText': "Don't have an account?",
        'auth.signIn.switchLink': 'Sign Up',
        'auth.signIn.error': 'Failed to log in. Please check your credentials.',

        'auth.signUp.title': 'Create Account',
        'auth.signUp.fullNameLabel': 'Full Name',
        'auth.signUp.emailLabel': 'Email Address',
        'auth.signUp.passwordLabel': 'Password',
        'auth.signUp.submit': 'Sign Up',
        'auth.signUp.loading': 'Creating Account...',
        'auth.signUp.switchText': 'Already have an account?',
        'auth.signUp.switchLink': 'Sign In',
        'auth.signUp.errorPrefix': 'Failed to create an account. ',

        'dashboard.welcome': 'Welcome back',
        'dashboard.subtitle': 'Here is an overview of notices, payments, and documents for your building.',
        'dashboard.recentNotices': 'Recent Notices',
        'dashboard.recentDocuments': 'Recent Documents',
        'dashboard.paymentControl': 'Payment Control',
        'dashboard.viewAll': 'View All',
        'dashboard.newAlertButton': '+ New Alert',
        'dashboard.loadingNotices': 'Loading notices...',
        'dashboard.noNotices': 'No active notices.',
        'dashboard.loadingPayments': 'Loading payments...',
        'dashboard.noPayments': 'No payment records.',
        'dashboard.loadingDocuments': 'Loading documents...',
        'dashboard.noDocuments': 'No documents available.',
        'dashboard.addPaymentRecord': '+ Add New Record',
        'dashboard.upload': 'Upload',
        'dashboard.noticeModal.title': 'Post New Alert',
        'dashboard.noticeModal.titleLabel': 'Title',
        'dashboard.noticeModal.contentLabel': 'Content',
        'dashboard.noticeModal.markUrgent': 'Mark as Urgent',
        'dashboard.noticeModal.submit': 'Post Notice',
        'dashboard.paymentModal.title': 'Create Payment Record',
        'dashboard.paymentModal.ownerLabel': 'Owner',
        'dashboard.paymentModal.unitLabel': 'Unit',
        'dashboard.paymentModal.monthLabel': 'Reference Month',
        'dashboard.paymentModal.amountLabel': 'Amount ($)',
        'dashboard.paymentModal.submit': 'Create Record',
        'dashboard.table.owner': 'Owner',
        'dashboard.table.unit': 'Unit',
        'dashboard.table.month': 'Month',
        'dashboard.table.status': 'Status',
        'dashboard.table.actions': 'Actions',
        'dashboard.searchPlaceholder': 'Search notices, payments, documents...',

        'notices.title': 'Notices & Alerts',
        'notices.newAlertButton': '+ New Alert',
        'notices.loading': 'Loading notices...',
        'notices.empty': 'No notices found.',
        'notices.modal.title': 'Post New Alert',
        'notices.modal.titleLabel': 'Title',
        'notices.modal.contentLabel': 'Content',
        'notices.modal.markUrgent': 'Mark as Urgent',
        'notices.modal.submit': 'Post Notice',

        'documents.title': 'Document Repository',
        'documents.uploadButton': 'Upload Document',
        'documents.loading': 'Loading documents...',
        'documents.empty': 'No documents available.',
        'documents.download': 'Download',

        'payments.title': 'Payment Control',
        'payments.loading': 'Loading payments...',
        'payments.empty': 'No payment records found.',
        'payments.table.owner': 'Owner',
        'payments.table.unit': 'Unit',
        'payments.table.month': 'Month',
        'payments.table.amount': 'Amount',
        'payments.table.status': 'Status',
        'payments.table.actions': 'Actions',
        'payments.addRecordButton': '+ Add Record',
        'payments.modal.title': 'Create Payment Record',
        'payments.modal.ownerLabel': 'Owner',
        'payments.modal.unitLabel': 'Unit',
        'payments.modal.monthLabel': 'Reference Month',
        'payments.modal.amountLabel': 'Amount ($)',
        'payments.modal.submit': 'Create Record',

        'profile.title': 'Profile',
        'profile.subtitle': 'Manage your personal information.',
        'profile.nameLabel': 'Name',
        'profile.emailLabel': 'Email',
        'profile.addressLabel': 'Address',
        'profile.phoneLabel': 'Phone',
        'profile.condominiumLabel': 'Condominium',
        'profile.condominiumUnassigned': 'Not assigned yet',
        'profile.condominiumHint': 'Only administrators can change your condominium.',
        'profile.saveButton': 'Save Changes',
        'profile.loading': 'Loading profile...',
        'profile.error.load': 'Failed to load profile',
        'profile.error.update': 'Failed to update profile',
        'profile.success.update': 'Profile updated successfully.',

        'condominium.title': 'Condominium',
        'condominium.subtitle': 'Basic information about your building.',
        'condominium.currentTitle': 'Current Condominium',
        'condominium.nameLabel': 'Name',
        'condominium.addressLabel': 'Address',
        'condominium.createdAtLabel': 'Created At',
        'condominium.saveButton': 'Save Changes',
        'condominium.noLink': 'Your account is not linked to any condominium yet.',
        'condominium.noDetails': 'No details found for this condominium.',
        'condominium.createTitle': 'Create New Condominium',
        'condominium.createSubtitle': 'Use this section to register additional condominiums in the system.',
        'condominium.createButton': 'Create Condominium',

        'users.title': 'User Management',
        'users.subtitle': 'Assign users to condominiums.',
        'users.searchPlaceholder': 'Search users...',
        'users.table.user': 'User',
        'users.table.contact': 'Contact',
        'users.table.condominium': 'Assigned Condominium',
        'users.table.role': 'Role',
        'users.noneFound': 'No users found matching',
        'users.accessDenied': 'Access Denied. Admin privileges required.',

        'documentsPage.deleteConfirm': 'Delete this document?',
        'noticesPage.deleteConfirm': 'Are you sure you want to delete this notice?',
        'paymentsPage.deleteConfirm': 'Are you sure?',

        'common.cancel': 'Cancel',

        // Empty States
        'emptyStates.notices.title': 'No notices yet',
        'emptyStates.notices.message': 'There are no notices or alerts at the moment. Check back later for updates from your condominium.',
        'emptyStates.payments.title': 'No payments recorded',
        'emptyStates.payments.message': 'No payment records have been added yet. Payment information will appear here once available.',
        'emptyStates.documents.title': 'No documents available',
        'emptyStates.documents.message': 'The document repository is empty. Important files and documents will be shared here.',
        'emptyStates.search.title': 'No results found',
        'emptyStates.noSearchResults': 'No items match your search criteria. Try adjusting your search terms.',

        // Confirm Dialog
        'confirmDialog.danger.title': 'Are you sure?',
        'confirmDialog.danger.message': 'This action cannot be undone. This will permanently delete the selected item.',
        'confirmDialog.danger.confirm': 'Delete',
        'confirmDialog.warning.title': 'Warning',
        'confirmDialog.warning.message': 'Please confirm this action.',
        'confirmDialog.warning.confirm': 'Confirm',
        'confirmDialog.info.title': 'Information',
        'confirmDialog.info.message': 'Please review and confirm.',
        'confirmDialog.info.confirm': 'OK',
        'confirmDialog.logout.title': 'Sign Out',
        'confirmDialog.logout.message': 'Are you sure you want to sign out?',
        'confirmDialog.logout.confirm': 'Sign Out',
        'common.processing': 'Processing...',

        // Table
        'table.noData': 'No data available',
        'table.actions': 'Actions',

        // Upload
        'upload.dragDrop': 'Drag and drop files here',
        'upload.dropHere': 'Drop files here!',
        'upload.orClick': 'or click to browse',
        'upload.maxSize': 'Max {size}',
        'upload.selectedFiles': 'Selected files',
        'upload.upload': 'Upload',
        'upload.uploading': 'Uploading...',
        'upload.completed': 'Completed!',
        'upload.remove': 'Remove file',
        'upload.error.size': 'File "{name}" exceeds max size of {size}',
        'upload.error.type': 'File "{name}" has invalid type',
        'upload.error.maxFiles': 'Maximum {max} files allowed',
        'upload.error.generic': 'Error uploading files. Please try again.'
    },
    pt: {
        'nav.dashboard': 'Painel',
        'nav.profile': 'Perfil',
        'nav.notices': 'Avisos',
        'nav.payments': 'Pagamentos',
        'nav.documents': 'Documentos',
        'nav.condominium': 'Condomínio',
        'nav.users': 'Utilizadores',
        'nav.signOut': 'Terminar sessão',
        'nav.languageToggle': 'EN',

        'auth.signIn.title': 'Bem-vindo de volta',
        'auth.signIn.emailLabel': 'Endereço de email',
        'auth.signIn.passwordLabel': 'Palavra-passe',
        'auth.signIn.submit': 'Entrar',
        'auth.signIn.loading': 'A entrar...',
        'auth.signIn.switchText': 'Ainda não tem conta?',
        'auth.signIn.switchLink': 'Registar',
        'auth.signIn.error': 'Falha ao iniciar sessão. Verifique as suas credenciais.',

        'auth.signUp.title': 'Criar conta',
        'auth.signUp.fullNameLabel': 'Nome completo',
        'auth.signUp.emailLabel': 'Endereço de email',
        'auth.signUp.passwordLabel': 'Palavra-passe',
        'auth.signUp.submit': 'Registar',
        'auth.signUp.loading': 'A criar conta...',
        'auth.signUp.switchText': 'Já tem conta?',
        'auth.signUp.switchLink': 'Entrar',
        'auth.signUp.errorPrefix': 'Falha ao criar conta. ',

        'dashboard.welcome': 'Bem-vindo de volta',
        'dashboard.subtitle': 'Aqui tem uma visão geral dos avisos, pagamentos e documentos do seu prédio.',
        'dashboard.recentNotices': 'Avisos recentes',
        'dashboard.recentDocuments': 'Documentos recentes',
        'dashboard.paymentControl': 'Controlo de pagamentos',
        'dashboard.viewAll': 'Ver tudo',
        'dashboard.newAlertButton': '+ Novo aviso',
        'dashboard.loadingNotices': 'A carregar avisos...',
        'dashboard.noNotices': 'Não existem avisos ativos.',
        'dashboard.loadingPayments': 'A carregar pagamentos...',
        'dashboard.noPayments': 'Não existem registos de pagamento.',
        'dashboard.loadingDocuments': 'A carregar documentos...',
        'dashboard.noDocuments': 'Não existem documentos.',
        'dashboard.addPaymentRecord': '+ Adicionar registo',
        'dashboard.upload': 'Carregar',
        'dashboard.noticeModal.title': 'Criar novo aviso',
        'dashboard.noticeModal.titleLabel': 'Título',
        'dashboard.noticeModal.contentLabel': 'Conteúdo',
        'dashboard.noticeModal.markUrgent': 'Marcar como urgente',
        'dashboard.noticeModal.submit': 'Publicar aviso',
        'dashboard.paymentModal.title': 'Criar registo de pagamento',
        'dashboard.paymentModal.ownerLabel': 'Proprietário',
        'dashboard.paymentModal.unitLabel': 'Unidade',
        'dashboard.paymentModal.monthLabel': 'Mês de referência',
        'dashboard.paymentModal.amountLabel': 'Valor (€)',
        'dashboard.paymentModal.submit': 'Criar registo',
        'dashboard.table.owner': 'Proprietário',
        'dashboard.table.unit': 'Unidade',
        'dashboard.table.month': 'Mês',
        'dashboard.table.status': 'Estado',
        'dashboard.table.actions': 'Ações',
        'dashboard.searchPlaceholder': 'Pesquisar avisos, pagamentos, documentos...',

        'notices.title': 'Avisos e alertas',
        'notices.newAlertButton': '+ Novo aviso',
        'notices.loading': 'A carregar avisos...',
        'notices.empty': 'Não existem avisos.',
        'notices.modal.title': 'Criar novo aviso',
        'notices.modal.titleLabel': 'Título',
        'notices.modal.contentLabel': 'Conteúdo',
        'notices.modal.markUrgent': 'Marcar como urgente',
        'notices.modal.submit': 'Publicar aviso',

        'documents.title': 'Repositório de documentos',
        'documents.uploadButton': 'Carregar documento',
        'documents.loading': 'A carregar documentos...',
        'documents.empty': 'Não existem documentos.',
        'documents.download': 'Descarregar',

        'payments.title': 'Controlo de pagamentos',
        'payments.loading': 'A carregar pagamentos...',
        'payments.empty': 'Não existem registos de pagamento.',
        'payments.table.owner': 'Proprietário',
        'payments.table.unit': 'Unidade',
        'payments.table.month': 'Mês',
        'payments.table.amount': 'Valor',
        'payments.table.status': 'Estado',
        'payments.table.actions': 'Ações',
        'payments.addRecordButton': '+ Adicionar registo',
        'payments.modal.title': 'Criar registo de pagamento',
        'payments.modal.ownerLabel': 'Proprietário',
        'payments.modal.unitLabel': 'Unidade',
        'payments.modal.monthLabel': 'Mês de referência',
        'payments.modal.amountLabel': 'Valor (€)',
        'payments.modal.submit': 'Criar registo',

        'profile.title': 'Perfil',
        'profile.subtitle': 'Gira a sua informação pessoal.',
        'profile.nameLabel': 'Nome',
        'profile.emailLabel': 'Email',
        'profile.addressLabel': 'Morada',
        'profile.phoneLabel': 'Telefone',
        'profile.condominiumLabel': 'Condomínio',
        'profile.condominiumUnassigned': 'Ainda não associado',
        'profile.condominiumHint': 'Só os administradores podem alterar o seu condomínio.',
        'profile.saveButton': 'Guardar alterações',
        'profile.loading': 'A carregar perfil...',
        'profile.error.load': 'Falha ao carregar perfil',
        'profile.error.update': 'Falha ao atualizar perfil',
        'profile.success.update': 'Perfil atualizado com sucesso.',

        'condominium.title': 'Condomínio',
        'condominium.subtitle': 'Informação básica sobre o seu prédio.',
        'condominium.currentTitle': 'Condomínio atual',
        'condominium.nameLabel': 'Nome',
        'condominium.addressLabel': 'Morada',
        'condominium.createdAtLabel': 'Criado em',
        'condominium.saveButton': 'Guardar alterações',
        'condominium.noLink': 'A sua conta ainda não está associada a nenhum condomínio.',
        'condominium.noDetails': 'Não existem detalhes para este condomínio.',
        'condominium.createTitle': 'Criar novo condomínio',
        'condominium.createSubtitle': 'Use esta secção para registar novos condomínios no sistema.',
        'condominium.createButton': 'Criar condomínio',

        'users.title': 'Gestão de utilizadores',
        'users.subtitle': 'Atribua utilizadores a condomínios.',
        'users.searchPlaceholder': 'Pesquisar utilizadores...',
        'users.table.user': 'Utilizador',
        'users.table.contact': 'Contacto',
        'users.table.condominium': 'Condomínio associado',
        'users.table.role': 'Função',
        'users.noneFound': 'Nenhum utilizador encontrado para',
        'users.accessDenied': 'Acesso negado. São necessários privilégios de administrador.',

        'documentsPage.deleteConfirm': 'Eliminar este documento?',
        'noticesPage.deleteConfirm': 'Tem a certeza que pretende eliminar este aviso?',
        'paymentsPage.deleteConfirm': 'Tem a certeza?',

        'common.cancel': 'Cancelar',

        // Empty States
        'emptyStates.notices.title': 'Sem avisos',
        'emptyStates.notices.message': 'De momento não existem avisos ou alertas. Volte mais tarde para ver atualizações do seu condomínio.',
        'emptyStates.payments.title': 'Sem pagamentos registados',
        'emptyStates.payments.message': 'Ainda não foram adicionados registos de pagamento. As informações de pagamento aparecerão aqui quando disponíveis.',
        'emptyStates.documents.title': 'Sem documentos disponíveis',
        'emptyStates.documents.message': 'O repositório de documentos está vazio. Ficheiros e documentos importantes serão partilhados aqui.',
        'emptyStates.search.title': 'Nenhum resultado encontrado',
        'emptyStates.noSearchResults': 'Nenhum item corresponde aos critérios de pesquisa. Tente ajustar os termos de pesquisa.',

        // Confirm Dialog
        'confirmDialog.danger.title': 'Tem a certeza?',
        'confirmDialog.danger.message': 'Esta ação não pode ser desfeita. Isto irá eliminar permanentemente o item selecionado.',
        'confirmDialog.danger.confirm': 'Eliminar',
        'confirmDialog.warning.title': 'Aviso',
        'confirmDialog.warning.message': 'Por favor confirme esta ação.',
        'confirmDialog.warning.confirm': 'Confirmar',
        'confirmDialog.info.title': 'Informação',
        'confirmDialog.info.message': 'Por favor reveja e confirme.',
        'confirmDialog.info.confirm': 'OK',
        'confirmDialog.logout.title': 'Terminar sessão',
        'confirmDialog.logout.message': 'Tem a certeza que pretende terminar a sessão?',
        'confirmDialog.logout.confirm': 'Terminar sessão',
        'common.processing': 'A processar...',

        // Table
        'table.noData': 'Não existem dados',
        'table.actions': 'Ações',

        // Upload
        'upload.dragDrop': 'Arraste e solte ficheiros aqui',
        'upload.dropHere': 'Solte os ficheiros aqui!',
        'upload.orClick': 'ou clique para procurar',
        'upload.maxSize': 'Máx {size}',
        'upload.selectedFiles': 'Ficheiros selecionados',
        'upload.upload': 'Carregar',
        'upload.uploading': 'A carregar...',
        'upload.completed': 'Concluído!',
        'upload.remove': 'Remover ficheiro',
        'upload.error.size': 'O ficheiro "{name}" excede o tamanho máximo de {size}',
        'upload.error.type': 'O ficheiro "{name}" tem um tipo inválido',
        'upload.error.maxFiles': 'Máximo de {max} ficheiros permitidos',
        'upload.error.generic': 'Erro ao carregar ficheiros. Por favor tente novamente.'
    }
};

export const LanguageContext = createContext({
    language: 'en',
    setLanguage: () => {},
    toggleLanguage: () => {},
    t: (key) => translations.en[key] || key
});

const LanguageProviderInner = ({ children }) => {
    const [language, setLanguage] = useState('en');

    const toggleLanguage = () => {
        setLanguage((prev) => (prev === 'en' ? 'pt' : 'en'));
    };

    const t = (key) => {
        const langTable = translations[language] || translations.en;
        return langTable[key] || translations.en[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const LanguageProvider = ({ children }) => (
    <LanguageProviderInner>{children}</LanguageProviderInner>
);

export const useLanguage = () => useContext(LanguageContext);
